name: Joel Calado
description: Blogging tech.
meta_description: "I love tech"

aboutPage: true

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]


paginate: 20
baseurl: /
domain_name: 'http://blog.joelcalado.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'jcalado'

# Details for the RSS feed generator
url:            'http://blog.joelcalado.com'
author:         'Joel Calado'
authorTwitter:  'jcalado'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
